services:
    postgres:
        image: postgres:13-alpine
        container_name: postgres
        restart: on-failure
        user: postgres
        volumes:
          - postgres-data:/var/lib/postgresql/data
        environment:
          POSTGRES_USER: ${PG_USER:-postgres}
          POSTGRES_PASSWORD: ${PG_PASSWORD:-postgres}
        ports:
          - '5432:5432'
volumes:
  postgres-data:
